before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    main: ./cmd/agent/
    binary: shieldwall-agent

archives:
  - id: archive
    name_template: "shieldwall-agent_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: 'tar.gz'
    files:
      - LICENSE.md
      - shieldwall-agent.service
      - update.sh
      - install.sh

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - 'typo'
      - '^test:'
      - 'misc: small fix or general refactoring i did not bother commenting'
